In [1]:
import numpy as np
from collections import Counter

In [362]:
# SET THIS TO LOAD EXAMPLE DATA INSTEAD

# example = True
example_small = True
# example = False

if example_small:
    fname = 'example_small.txt'
elif example:
    fname = 'example.txt'
else:
    fname = 'input.txt'

with open(fname) as f:
    lines = f.readlines()

data = []
for line in lines:
#     print(line)
#     print(line.split(' | '))
#     a, b = line.split(' | ')
    first, second = line.split(' | ')
#     print(first, second)
#     print([bunch.strip() for bunch in first.split(' ')])
    data.append( ([bunch.strip() for bunch in first.split(' ')], [bunch.strip() for bunch in second.split(' ')]) )


In [363]:

data

[(['acedgfb',
   'cdfbe',
   'gcdfa',
   'fbcad',
   'dab',
   'cefabd',
   'cdfgeb',
   'eafb',
   'cagedb',
   'ab'],
  ['cdfeb', 'fcadb', 'cdfeb', 'cdbaf'])]

In [226]:
for _, outputs in data[0:1]:
    print(outputs)

['fdgacbe', 'cefdb', 'cefbgd', 'gcbe']


In [227]:
sum([(len(signals) == 2 or len(signals) == 3 or len(signals) == 4 or len(signals) == 7) for _, outputs in data for signals in outputs ])

26

In [69]:
# credit https://stackoverflow.com/a/40891978/16928241
import numpy as np
import itertools as it
import math
def myPerms(k):
    f_k=math.factorial(k)
#   A=np.empty((k,f_k))
    A=np.empty((f_k,k))
    for i,perm in enumerate(it.permutations(range(k))):
        A[i,:] = perm
#     A+=1
    return A.astype(int)

all_perms = myPerms(7)
print(all_perms)

[[0 1 2 ... 4 5 6]
 [0 1 2 ... 4 6 5]
 [0 1 2 ... 5 4 6]
 ...
 [6 5 4 ... 1 2 0]
 [6 5 4 ... 2 0 1]
 [6 5 4 ... 2 1 0]]


In [67]:
len(all_perms)

5040

In [ ]:
# method 2...

In [ ]:
# all_perms is 'orders' of signals to the same segments...
# some_array[order] = segments


In [269]:
num_patterns = [
    'abcefg', # 0
    'cf', # 1
    'acdeg', # 2
    'acdfg', # 3
    'bcdf', # 4
    'abdfg', # 5
    'abdefg', # 6
    'acf', # 7
    'abcdefg', # 8
    'abcdfg', # 9
]

num_patterns_2 = [[[ord(char)-97 for char in pattern] for pattern in num_patterns] for perm in all_perms[0:2]]
num_patterns_2 = [[ord(char)-97 for char in pattern] for pattern in num_patterns]

# 7 should go from acf to acg in perms[1]

num_patterns_2

[[0, 1, 2, 4, 5, 6],
 [2, 5],
 [0, 2, 3, 4, 6],
 [0, 2, 3, 5, 6],
 [1, 2, 3, 5],
 [0, 1, 3, 5, 6],
 [0, 1, 3, 4, 5, 6],
 [0, 2, 5],
 [0, 1, 2, 3, 4, 5, 6],
 [0, 1, 2, 3, 5, 6]]

In [283]:
# signals x digit array
signals_digit = np.full((7, 10), 0)

for digit, segments in enumerate(num_patterns_2):
    signals_digit[segments, digit] = 1


signals_digit = np.array(signals_digit)
signals_digit

array([[1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1]])

In [286]:
np.eye(7).astype(int).dot(signals_digit)

array([[1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 1, 1]])

In [338]:
temp_all_signals_digts = np.eye(7).astype(int)[:,all_perms].dot(signals_digit)
print(temp_all_signals_digts.shape)
temp_all_signals_digts.transpose([1, 0, 2])[0].shape

(7, 5040, 10)


(7, 10)

In [339]:
temp_signals_digits = np.eye(7).astype(int).dot(signals_digit)

print(["".join([letter for letter, include in zip('abcdefg', row) if include]) for row in temp_signals_digts.T])


['abcefg', 'cf', 'acdeg', 'acdfg', 'bcdf', 'abdfg', 'abdefg', 'acf', 'abcdefg', 'abcdfg']


In [342]:
all_signals_digits = np.eye(7).astype(int)[:,all_perms].dot(signals_digit).transpose([1, 0, 2])

# print(all_signals_digts[:,0,:])

all_perm_maps = [["".join([letter for letter, include in zip('abcdefg', row) if include]) for row in perm.T] for perm in all_signals_digits]
all_perm_maps[0:2]

[['abcefg',
  'cf',
  'acdeg',
  'acdfg',
  'bcdf',
  'abdfg',
  'abdefg',
  'acf',
  'abcdefg',
  'abcdfg'],
 ['abcefg',
  'cg',
  'acdef',
  'acdfg',
  'bcdg',
  'abdfg',
  'abdefg',
  'acg',
  'abcdefg',
  'abcdfg']]

In [ ]:
np.eye(7).astype(int)[:,all_perms[1]].dot(signals_digit)

# all garbage below

In [155]:
num_patterns = [
    'abcefg', # 0
    'cf', # 1
    'acdeg', # 2
    'acdfg', # 3
    'bcdf', # 4
    'abdfg', # 5
    'abdefg', # 6
    'acf', # 7
    'abcdefg', # 8
    'abcdfg', # 9
]

num_patterns = np.array([list(pat+" "*(7-len(pat))) for pat in num_patterns])
num_patterns, num_patterns.shape

(array([['a', 'b', 'c', 'e', 'f', 'g', ' '],
        ['c', 'f', ' ', ' ', ' ', ' ', ' '],
        ['a', 'c', 'd', 'e', 'g', ' ', ' '],
        ['a', 'c', 'd', 'f', 'g', ' ', ' '],
        ['b', 'c', 'd', 'f', ' ', ' ', ' '],
        ['a', 'b', 'd', 'f', 'g', ' ', ' '],
        ['a', 'b', 'd', 'e', 'f', 'g', ' '],
        ['a', 'c', 'f', ' ', ' ', ' ', ' '],
        ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
        ['a', 'b', 'c', 'd', 'f', 'g', ' ']], dtype='<U1'),
 (10, 7))

In [157]:
test = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])
test[all_perms]

array([['a', 'b', 'c', ..., 'e', 'f', 'g'],
       ['a', 'b', 'c', ..., 'e', 'g', 'f'],
       ['a', 'b', 'c', ..., 'f', 'e', 'g'],
       ...,
       ['g', 'f', 'e', ..., 'b', 'c', 'a'],
       ['g', 'f', 'e', ..., 'c', 'a', 'b'],
       ['g', 'f', 'e', ..., 'c', 'b', 'a']], dtype='<U1')

In [161]:
num_patterns[:,all_perms]

array([[['a', 'b', 'c', ..., 'f', 'g', ' '],
        ['a', 'b', 'c', ..., 'f', ' ', 'g'],
        ['a', 'b', 'c', ..., 'g', 'f', ' '],
        ...,
        [' ', 'g', 'f', ..., 'b', 'c', 'a'],
        [' ', 'g', 'f', ..., 'c', 'a', 'b'],
        [' ', 'g', 'f', ..., 'c', 'b', 'a']],

       [['c', 'f', ' ', ..., ' ', ' ', ' '],
        ['c', 'f', ' ', ..., ' ', ' ', ' '],
        ['c', 'f', ' ', ..., ' ', ' ', ' '],
        ...,
        [' ', ' ', ' ', ..., 'f', ' ', 'c'],
        [' ', ' ', ' ', ..., ' ', 'c', 'f'],
        [' ', ' ', ' ', ..., ' ', 'f', 'c']],

       [['a', 'c', 'd', ..., 'g', ' ', ' '],
        ['a', 'c', 'd', ..., 'g', ' ', ' '],
        ['a', 'c', 'd', ..., ' ', 'g', ' '],
        ...,
        [' ', ' ', 'g', ..., 'c', 'd', 'a'],
        [' ', ' ', 'g', ..., 'd', 'a', 'c'],
        [' ', ' ', 'g', ..., 'd', 'c', 'a']],

       ...,

       [['a', 'c', 'f', ..., ' ', ' ', ' '],
        ['a', 'c', 'f', ..., ' ', ' ', ' '],
        ['a', 'c', 'f', ..., ' ', ' ', ' '

In [166]:
num_patterns[:,all_perms].shape

(10, 5040, 7)

In [364]:
# for _, outputs in data[0:1]:
#     print(outputs)

test = ["".join(sorted(outs)) for outs in data[0][0]]
test

['abcdefg',
 'bcdef',
 'acdfg',
 'abcdf',
 'abd',
 'abcdef',
 'bcdefg',
 'abef',
 'abcdeg',
 'ab']

In [365]:
# [sum(ta in pattern for ta in test) for pattern in all_patterns]
max_matches = 0
for perm_idx, pattern in enumerate(all_perm_maps):
    matches = sum(ta in pattern for ta in test)
    if matches > max_matches:
#         print(matches)
        max_matches = matches
#         print(pattern)
    if matches == len(test):
        print("success!", pattern, perm_idx, matches)
            

success! ['abcdeg', 'ab', 'acdfg', 'abcdf', 'abef', 'bcdef', 'bcdefg', 'abd', 'abcdefg', 'abcdef'] 2536 10


In [ ]:
def get_map(inputs):
    

In [83]:
result = 0
for inputs, outputs in data:
    signal_map = get_map(inputs)
    result += sum(map(signal_map, outputs))
result

NameError: name 'get_map' is not defined