In [36]:
import numpy as np

In [173]:
# SET THIS TO LOAD EXAMPLE DATA INSTEAD
# example = True
example = False

if example:
    fname = 'example.txt'
else:
    fname = 'input.txt'

with open(fname) as f:
    lines = f.readlines()

# 
def load_line(line): 
    return [int(char) for char in line.strip()]
    
inputs = [load_line(line) for line in lines]

In [174]:
inputs = np.array(inputs)
inputs

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 0, 1, 0]])

In [175]:
inputs.mean(axis=0)

array([0.498, 0.483, 0.484, 0.509, 0.508, 0.495, 0.491, 0.497, 0.507,
       0.495, 0.505, 0.498])

In [164]:

a = inputs.mean(axis=0) >= 0.5
# b = ~a.copy()
b = inputs.mean(axis=0) <= 0.5

a, b

(array([False, False, False,  True,  True, False, False, False,  True,
        False,  True, False]),
 array([ True,  True,  True, False, False,  True,  True,  True, False,
         True, False,  True]))

In [165]:
a_dec = int("".join(['1' if char else '0' for char in a]), 2)
b_dec = int("".join(['1' if char else '0' for char in b]), 2)
prod = a_dec * b_dec

In [166]:
prod

1458194

In [167]:
a

array([False, False, False,  True,  True, False, False, False,  True,
       False,  True, False])

In [168]:
(inputs[:,0] == 1) & (inputs[:,1] == 0)

array([False, False, False, False, False, False, False,  True, False,
        True,  True, False, False,  True,  True,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False,  True, False,  True,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False, False, False,  True, False, False,  True, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False, False,  True, False, False, False, False,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
        True,  True,

In [169]:
idx = np.alltrue(inputs.shape)
for ii in range(inputs.shape[1]):
    print(ii)
    idx &= (inputs[:,ii] == a[ii])
    if idx.sum() == 1:
        break

a_ans = inputs[idx][0]
print(a_ans)
c_dec = int("".join(['1' if char else '0' for char in a_ans]), 2)
print(c_dec)

0
1
2
3
4
5
6
7
8
9
[0 0 0 1 1 0 0 0 1 0 0 1]
393


In [170]:
idx = np.array([True] * len(inputs))
for ii in range(inputs.shape[1]):
    mc = inputs[idx, ii].mean(axis=0) >= 0.5 # new most common
    idx &= (inputs[:,ii] == mc)
    if idx.sum() == 1:
        break

a_ans = inputs[idx][0]
print(a_ans)
c_dec = int("".join(['1' if char else '0' for char in a_ans]), 2)
print(c_dec)

[0 0 1 1 0 0 0 1 0 1 0 1]
789


In [171]:
idx = np.array([True] * len(inputs))
for ii in range(inputs.shape[1]):

    lc = inputs[idx, ii].mean(axis=0) < 0.5
#     print(f"{mc=}")
    #
    idx &= (inputs[:,ii] == lc)
    print(f"{ii=}, {idx.sum()=}")
    if idx.sum() == 1:
        break

b_ans = inputs[idx][0]
print(b_ans)
d_dec = int("".join(['1' if char else '0' for char in b_ans]), 2)
print(d_dec)

ii=0, idx.sum()=498
ii=1, idx.sum()=246
ii=2, idx.sum()=114
ii=3, idx.sum()=56
ii=4, idx.sum()=24
ii=5, idx.sum()=10
ii=6, idx.sum()=4
ii=7, idx.sum()=2
ii=8, idx.sum()=1
[1 1 1 0 0 0 0 0 0 0 1 0]
3586


In [172]:
c_dec * d_dec

2829354